---
- name: Install and Start Apache2
  hosts: webservers
  become: yes
  remote_user: devops
  tasks:
    - name: Run apt-get update
      apt:
        update_cache: yes

    - name: Install Apache2
      apt: 
        name: apache2
        state: present

    - name: Start and enable Apache2 service
      systemd:
        name: apache2
        state: restarted
        enabled: yes

