---
- name: Install and configure Nginx
  hosts: webservers
  become: yes
  remote_user: devops
  tasks:
    - name: Update package cache (Debian-based systems)
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache for 1 hour
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    # - name: Stop Nginx
    #   systemd:
    #     name: nginx
    #     state: stopped

    # - name: Uninstall Nginx
    #   apt:
    #     name: nginx
    #     state: absent
    #     purge: yes
    #     autoremove: yes

