# [web]
# host-1 ansible_host=172.31.3.46
# host-2 ansible_host=172.31.11.62
# host-3 ansible_host=172.31.28.37

---
- name: First play
  become: true
  hosts: web
  tasks:
    - name: Install tmux
      package:
        name: tmux
        state: present

- name: Second play
  become: true
  hosts: host-1
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
